type navbar = { id: number; text: string }[];
type techname = {
  id: number;
  techname:
    | "nextjs"
    | "typscript"
    | "react"
    | "redux"
    | "tailwind"
    | "jest"
    | "javascript"
    | "sequelize"
    | "mysql"
    | "nodejs"
    | "expressjs"
    | "css"
    | "sqlite"
    | "postgres"
    | "aws"
    | "html"
    | "docker"
    | "azure"
    | "csharp"
    | "java"
    | "python"
    | "comm"
    | "team"
    | "prob"
    | "grow"
    | "rese"
    | "teac"
    | "sql"
    | "mongodb"
    | "prisma"
    | "figma"
    |"chartjs"
}[];
