import {
  NextJs,
  Typescript,
  Reactjs,
  Reduxjs,
  Tailwindcss,
  Jest,
  Javascript,
  Sequelize,
  Mysql,
  Postgress,
  Aws,
  Azure,
  Sqlite3,
  MongoDb,
  Prisma,
  Nodejs,
  Expressjs,
  HtmlIcon,
  CssIcon,
  Java,
  Csharp,
  Python,
  Docker,
  SQL,
  Communication,
  TeamWork,
  ProblemSolving,
  GrowthMindSet,
  Research,
  Teaching,
} from "../Icons/IconComponents/Icons";
import styles from "./Helper.module.css";

const Helper = () => {
  const LookUp = {
    nextjs: <NextJs />,
    typscript: <Typescript />,
    react: <Reactjs />,
    redux: <Reduxjs />,
    tailwind: <Tailwindcss />,
    jest: <Jest />,
    javascript: <Javascript />,
    sequelize: <Sequelize />,
    mysql: <Mysql />,
    postgres: <Postgress />,
    aws: <Aws />,
    azure: <Azure />,
    sqlite: <Sqlite3 />,
    mongodb:<MongoDb/>,
    prisma:<Prisma/>,
    nodejs: <Nodejs />,
    expressjs: <Expressjs />,
    html: <HtmlIcon />,
    css: <CssIcon />,
    csharp: <Csharp />,
    java: <Java />,
    python: <Python />,
    docker: <Docker />,
    sql:<SQL/>,
    comm: <Communication className={styles.adjustsize} />,
    team: <TeamWork className={styles.adjustsize} />,
    prob: <ProblemSolving className={styles.adjustsize} />,
    grow: <GrowthMindSet className={styles.adjustsize} />,
    rese: <Research className={styles.adjustsize} />,
    teac: <Teaching className={styles.adjustsize} />,
  };
  return LookUp;
};

export default Helper;
