import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { Montserrat, Architects_Daughter, Poppins } from "next/font/google";
import type { Metadata } from "next";
import Footer from "./components/Footer/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  about,
  skills,
  experiances,
  educations,
}: {
  children: React.ReactNode;
  about: React.ReactNode;
  skills: React.ReactNode;
  experiances: React.ReactNode;
  educations: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NavBar />
        {children}
        <div>{about}</div>
        <div>{skills}</div>
        <div>{experiances}</div>
        <div>{educations}</div>
        <Footer/>
      </body>
    </html>
  );
}
