import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { Montserrat, Architects_Daughter, Poppins } from "next/font/google";
import type { Metadata } from "next";
import Footer from "./components/Footer/Footer";
import TransitionEffect from "./components/TransitionEffect/TransitionEffect";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: 'swap',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NavBar />
        <TransitionEffect/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
